# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55e03d99db1112e3bc3fe72104bd681d6f5c4a9043fa5cc7048b027934691182a0d9cde1b89261972df4e6a3fa2eb28ce7296f6bfa253cba7ae4b47d68a4ad42

test:
  secret_key_base: 827af521aa1db5ab812c19f01c1007da507e9b2bf247df7770766ff771733486a1bd9981859860385a49ccf6575471c837061cfa026f13ce611bb399021c90a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
